# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 968a56a26b26b1532816f3cabe3f8df08b456058ef0cb7c3bfeaaccf3d68e397ec55b22f4abd3b53e9e4049aef3be9d287ea38a0988450e3a579c8dcec869797

test:
  secret_key_base: a78848a8aad61c52f7e1fd8f98d03107908e6f2a6baa7ca4719f3d5948de4e320b2f22ed4d4ebf0601d1068d883f0166defbb77178f02e7d74e668a92058d62d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
